#!/usr/bin/env bash
# Limbo Setup — Auth onboarding wizard
# Supports: Claude Code subscription, Codex subscription, OpenRouter, Anthropic API key
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput &>/dev/null && tput setaf 1 &>/dev/null; then
  C_RESET="$(tput sgr0)"
  C_BOLD="$(tput bold)"
  C_CYAN="$(tput setaf 6)"
  C_GREEN="$(tput setaf 2)"
  C_YELLOW="$(tput setaf 3)"
  C_RED="$(tput setaf 1)"
else
  C_RESET="" C_BOLD="" C_CYAN="" C_GREEN="" C_YELLOW="" C_RED=""
fi

h1()   { echo; echo "${C_BOLD}${C_CYAN}$*${C_RESET}"; echo; }
ok()   { echo "${C_GREEN}✓${C_RESET} $*"; }
warn() { echo "${C_YELLOW}!${C_RESET} $*"; }
die()  { echo "${C_RED}✗ $*${C_RESET}" >&2; exit 1; }

# ── Prereqs ───────────────────────────────────────────────────────────────────
check_prereqs() {
  local missing=()
  command -v docker &>/dev/null  || missing+=("docker")
  command -v npx    &>/dev/null  || missing+=("npx (Node.js)")
  if [ ${#missing[@]} -gt 0 ]; then
    die "Missing prerequisites: ${missing[*]}\nInstall them, then re-run this script."
  fi
}

# ── openclaw helper ───────────────────────────────────────────────────────────
# Always uses the locally installed openclaw if present, else falls back to
# the version bundled in the limbo Docker image (avoids forcing a global install).
OC_TEMP_DIR=""
cleanup() { [ -z "$OC_TEMP_DIR" ] || rm -rf "$OC_TEMP_DIR"; }
trap cleanup EXIT

run_openclaw() {
  if command -v openclaw &>/dev/null; then
    openclaw "$@"
  else
    # Use openclaw from the limbo image; mount a temp dir for state
    if [ -z "$OC_TEMP_DIR" ]; then
      OC_TEMP_DIR="$(mktemp -d)"
    fi
    docker run --rm -it \
      -v "$OC_TEMP_DIR:/home/limbo/.openclaw" \
      -e HOME=/home/limbo \
      limbo:local \
      openclaw "$@"
  fi
}

# After the wizard writes auth-profiles.json, extract a specific key from a profile
extract_key() {
  local profile_key="$1"   # e.g. "openrouter:default"
  local profiles_file

  if command -v openclaw &>/dev/null; then
    # Use default openclaw state dir
    profiles_file="${OPENCLAW_STATE_DIR:-$HOME/.openclaw}/agents/main/agent/auth-profiles.json"
  else
    profiles_file="$OC_TEMP_DIR/agents/main/agent/auth-profiles.json"
  fi

  if [ ! -f "$profiles_file" ]; then
    echo ""
    return
  fi

  # Extract via node (already a prereq via npx)
  node -e "
    const p = require('fs').readFileSync('$profiles_file', 'utf8');
    const j = JSON.parse(p);
    const profile = j.profiles['$profile_key'];
    if (profile && profile.key) {
      process.stdout.write(profile.key);
    }
  " 2>/dev/null || echo ""
}

# ── Write .env ────────────────────────────────────────────────────────────────
write_env() {
  local llm_api_key="$1"
  local model_provider="$2"
  local model_name="$3"
  local telegram_bot_token="${4:-}"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
LLM_API_KEY=${llm_api_key}
MODEL_PROVIDER=${model_provider}
MODEL_NAME=${model_name}
EOF

  if [ -n "$telegram_bot_token" ]; then
    cat >> "$ENV_FILE" <<EOF
TELEGRAM_ENABLED=true
TELEGRAM_BOT_TOKEN=${telegram_bot_token}
EOF
  else
    cat >> "$ENV_FILE" <<EOF
TELEGRAM_ENABLED=false
TELEGRAM_BOT_TOKEN=
EOF
  fi

  ok ".env written to $ENV_FILE"
}

# ── Auth flows ────────────────────────────────────────────────────────────────

auth_claude_code() {
  h1 "Claude Code Subscription Setup"
  echo "This will open a browser for you to authenticate with your Claude Code subscription."
  echo "After login, Anthropic will redirect you to a callback URL."
  echo "Copy and paste that callback URL when prompted."
  echo
  echo "Running: openclaw onboard --auth-choice setup-token"
  echo
  run_openclaw onboard --auth-choice setup-token \
    --skip-channels --skip-daemon --skip-skills --skip-health --skip-search --skip-ui || true

  # Extract from auth-profiles
  local api_key
  api_key="$(extract_key "anthropic:manual")"

  if [ -z "$api_key" ]; then
    # Try alternate profile key names that openclaw might use
    api_key="$(extract_key "anthropic:setup-token")" 2>/dev/null || true
  fi

  if [ -z "$api_key" ]; then
    echo
    warn "Could not auto-extract the API key from openclaw config."
    echo "If the OAuth flow completed, you can find the token in:"
    echo "  ~/.openclaw/agents/main/agent/auth-profiles.json"
    echo
    read -rp "Paste your Anthropic API key here: " api_key
  fi

  [ -n "$api_key" ] || die "No API key provided — exiting."

  read -rp "Model name [claude-sonnet-4-6]: " model_name
  model_name="${model_name:-claude-sonnet-4-6}"

  write_env "$api_key" "anthropic" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_codex() {
  h1 "Codex Subscription Setup"
  echo "This will open a browser for you to authenticate with your OpenAI Codex subscription."
  echo
  echo "Running: openclaw onboard --auth-choice openai-codex"
  echo
  run_openclaw onboard --auth-choice openai-codex \
    --skip-channels --skip-daemon --skip-skills --skip-health --skip-search --skip-ui || true

  # Extract from auth-profiles
  local api_key
  api_key="$(extract_key "openai:manual")" 2>/dev/null || true

  if [ -z "$api_key" ]; then
    api_key="$(extract_key "openai-codex:default")" 2>/dev/null || true
  fi

  if [ -z "$api_key" ]; then
    echo
    warn "Could not auto-extract the key from openclaw config."
    echo
    read -rp "Paste your OpenAI API key / Codex token here: " api_key
  fi

  [ -n "$api_key" ] || die "No API key provided — exiting."

  read -rp "Model name [gpt-4o]: " model_name
  model_name="${model_name:-gpt-4o}"

  write_env "$api_key" "openai" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_openrouter() {
  h1 "OpenRouter API Key Setup"
  echo "Get your key at: https://openrouter.ai/keys"
  echo
  read -rp "OpenRouter API key (sk-or-...): " api_key
  [ -n "$api_key" ] || die "No key provided."

  echo
  echo "OpenRouter model — leave blank for auto-routing."
  echo "Examples: anthropic/claude-sonnet-4-6  openai/gpt-4o  google/gemini-pro"
  read -rp "Model [auto]: " model_name
  model_name="${model_name:-auto}"

  write_env "$api_key" "openrouter" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_anthropic_key() {
  h1 "Anthropic API Key Setup"
  echo "Get your key at: https://console.anthropic.com/settings/keys"
  echo
  read -rp "Anthropic API key (sk-ant-...): " api_key
  [ -n "$api_key" ] || die "No key provided."

  read -rp "Model name [claude-sonnet-4-6]: " model_name
  model_name="${model_name:-claude-sonnet-4-6}"

  write_env "$api_key" "anthropic" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

# ── Telegram (optional) ───────────────────────────────────────────────────────
ask_telegram() {
  h1 "Telegram (optional)"
  echo "Connect a Telegram bot so you can chat with Limbo from your phone."
  echo "Create a bot at https://t.me/BotFather and paste the token."
  echo
  read -rp "Telegram bot token (or press Enter to skip): " TELEGRAM_BOT_TOKEN
  export TELEGRAM_BOT_TOKEN
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  clear 2>/dev/null || true

  echo "${C_BOLD}"
  cat <<'BANNER'
  ██╗     ██╗███╗   ███╗██████╗  ██████╗
  ██║     ██║████╗ ████║██╔══██╗██╔═══██╗
  ██║     ██║██╔████╔██║██████╔╝██║   ██║
  ██║     ██║██║╚██╔╝██║██╔══██╗██║   ██║
  ███████╗██║██║ ╚═╝ ██║██████╔╝╚██████╔╝
  ╚══════╝╚═╝╚═╝     ╚═╝╚═════╝  ╚═════╝
BANNER
  echo "${C_RESET}"
  echo "${C_BOLD}Personal memory agent setup${C_RESET}"
  echo

  check_prereqs

  # Check if .env exists
  if [ -f "$ENV_FILE" ]; then
    warn ".env already exists. This will overwrite it."
    read -rp "Continue? [y/N] " ans
    [[ "$ans" =~ ^[Yy] ]] || { echo "Aborted."; exit 0; }
  fi

  h1 "Choose your AI provider"
  echo "  1) Claude Code subscription  ${C_CYAN}(best quality, uses your existing sub)${C_RESET}"
  echo "  2) Codex subscription        ${C_CYAN}(uses your OpenAI sub)${C_RESET}"
  echo "  3) OpenRouter                ${C_CYAN}(access to 100+ models)${C_RESET}"
  echo "  4) Anthropic API key         ${C_CYAN}(direct, pay-per-use)${C_RESET}"
  echo
  read -rp "Choice [1-4]: " choice

  ask_telegram

  case "$choice" in
    1) auth_claude_code ;;
    2) auth_codex       ;;
    3) auth_openrouter  ;;
    4) auth_anthropic_key ;;
    *) die "Invalid choice: $choice" ;;
  esac

  echo
  h1 "You're set up."
  ok "Auth configured"
  ok ".env ready"
  echo
  echo "Start Limbo with:"
  echo "  ${C_BOLD}docker compose up -d${C_RESET}"
  echo
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    echo "Your Telegram bot is ready. Send it a message to pair."
    echo
  fi
}

main "$@"
