#!/usr/bin/env bash
# Limbo Setup — Auth onboarding wizard
# Supports: Claude Code subscription, Codex subscription, OpenRouter, Anthropic API key
#
# Usage: ./scripts/setup.sh
#   Guides you through picking an auth method, obtains credentials, and writes .env.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"

# ── Colors ────────────────────────────────────────────────────────────────────
if [ -t 1 ] && command -v tput &>/dev/null && tput setaf 1 &>/dev/null; then
  C_RESET="$(tput sgr0)"
  C_BOLD="$(tput bold)"
  C_CYAN="$(tput setaf 6)"
  C_GREEN="$(tput setaf 2)"
  C_YELLOW="$(tput setaf 3)"
  C_RED="$(tput setaf 1)"
else
  C_RESET="" C_BOLD="" C_CYAN="" C_GREEN="" C_YELLOW="" C_RED=""
fi

h1()   { echo; echo "${C_BOLD}${C_CYAN}══ $* ══${C_RESET}"; echo; }
ok()   { echo "${C_GREEN}✓${C_RESET} $*"; }
warn() { echo "${C_YELLOW}!${C_RESET} $*"; }
info() { echo "  $*"; }
die()  { echo "${C_RED}✗ $*${C_RESET}" >&2; exit 1; }

# ── Prereqs ───────────────────────────────────────────────────────────────────
check_prereqs() {
  command -v docker &>/dev/null || die "docker is required. Install it from https://docs.docker.com/get-docker/"
}

# ── .env writer ───────────────────────────────────────────────────────────────
write_env() {
  local llm_api_key="$1"
  local model_provider="$2"
  local model_name="$3"
  local telegram_bot_token="${4:-}"

  cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup.sh — $(date -u '+%Y-%m-%dT%H:%M:%SZ')
LLM_API_KEY=${llm_api_key}
MODEL_PROVIDER=${model_provider}
MODEL_NAME=${model_name}
TELEGRAM_ENABLED=${telegram_bot_token:+true}${telegram_bot_token:-false}
TELEGRAM_BOT_TOKEN=${telegram_bot_token}
EOF
  chmod 600 "$ENV_FILE"
  ok ".env written → $ENV_FILE"
}

# ── Require non-empty input ───────────────────────────────────────────────────
prompt_required() {
  local varname="$1"
  local label="$2"
  local value=""
  while [ -z "$value" ]; do
    read -rp "  ${label}: " value
    [ -n "$value" ] || warn "Required — try again."
  done
  printf -v "$varname" '%s' "$value"
}

# ── Auth flows ────────────────────────────────────────────────────────────────

auth_claude_code() {
  h1 "Claude Code Subscription"

  if ! command -v claude &>/dev/null; then
    warn "claude CLI not found."
    echo
    info "To use your Claude subscription you need the Claude Code CLI installed."
    info "Install it: https://claude.ai/download  (or: npm install -g @anthropic-ai/claude-code)"
    echo
    info "Once installed, run:  claude setup-token"
    info "It will print a long-lived API key (starts with sk-ant-)."
    info "Then paste it below."
    echo
  else
    # Check auth status
    local auth_method
    auth_method="$(CLAUDECODE="" claude auth status --json 2>/dev/null | node -e "
      const s = require('fs').readFileSync(0,'utf8');
      try { const j = JSON.parse(s); process.stdout.write(j.authMethod || ''); } catch { }
    " 2>/dev/null || echo "")"

    if [ -z "$auth_method" ]; then
      warn "Not logged in to Claude. Running: claude auth login"
      echo
      CLAUDECODE="" claude auth login || die "Login failed. Re-run setup after logging in."
      echo
    fi

    echo "${C_BOLD}Step 1:${C_RESET} Generate a long-lived API key from your subscription."
    echo
    info "Running: ${C_BOLD}claude setup-token${C_RESET}"
    info "This will:"
    info "  • Open a browser (or show an auth URL) for you to confirm"
    info "  • After you approve, print your API key in the terminal"
    echo
    read -rp "  Press Enter to run claude setup-token → " _
    echo

    # Run it — inherits the terminal so the user sees the full interactive flow
    CLAUDECODE="" claude setup-token || true

    echo
    echo "${C_BOLD}Step 2:${C_RESET} Copy the key printed above (starts with ${C_CYAN}sk-ant-${C_RESET})."
  fi

  echo
  local api_key
  prompt_required api_key "Paste your API key"
  [[ "$api_key" == sk-ant-* ]] || warn "Key doesn't look like an Anthropic token — proceeding anyway."

  local model_name
  read -rp "  Model name [claude-sonnet-4-6]: " model_name
  model_name="${model_name:-claude-sonnet-4-6}"

  write_env "$api_key" "anthropic" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_codex() {
  h1 "Codex (OpenAI) Subscription"

  if command -v codex &>/dev/null; then
    echo "${C_BOLD}Step 1:${C_RESET} Generate an API token from your Codex subscription."
    echo
    info "Running: ${C_BOLD}codex setup-token${C_RESET}"
    echo
    read -rp "  Press Enter to run codex setup-token → " _
    echo

    codex setup-token 2>&1 || true

    echo
    echo "${C_BOLD}Step 2:${C_RESET} Copy the key printed above."
  else
    warn "codex CLI not found."
    echo
    info "You can get an OpenAI API key at: https://platform.openai.com/api-keys"
    info "Or install Codex CLI and run: codex setup-token"
    echo
  fi

  local api_key
  prompt_required api_key "Paste your OpenAI / Codex API key"

  local model_name
  read -rp "  Model name [gpt-4o]: " model_name
  model_name="${model_name:-gpt-4o}"

  write_env "$api_key" "openai" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_openrouter() {
  h1 "OpenRouter"

  info "Get your key at: ${C_CYAN}https://openrouter.ai/keys${C_RESET}"
  info "OpenRouter gives you access to 100+ models with one key."
  echo

  local api_key
  prompt_required api_key "OpenRouter API key (sk-or-...)"
  [[ "$api_key" == sk-or-* ]] || warn "Key doesn't look like an OpenRouter key — proceeding anyway."

  echo
  info "Model — leave blank for OpenRouter's auto-routing."
  info "Examples: ${C_CYAN}anthropic/claude-sonnet-4-6  openai/gpt-4o  google/gemini-pro${C_RESET}"
  local model_name
  read -rp "  Model [auto]: " model_name
  model_name="${model_name:-auto}"

  write_env "$api_key" "openrouter" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

auth_anthropic_key() {
  h1 "Anthropic API Key"

  info "Get your key at: ${C_CYAN}https://console.anthropic.com/settings/keys${C_RESET}"
  echo

  local api_key
  prompt_required api_key "Anthropic API key (sk-ant-...)"
  [[ "$api_key" == sk-ant-* ]] || warn "Key doesn't look like an Anthropic key — proceeding anyway."

  local model_name
  read -rp "  Model name [claude-sonnet-4-6]: " model_name
  model_name="${model_name:-claude-sonnet-4-6}"

  write_env "$api_key" "anthropic" "$model_name" "${TELEGRAM_BOT_TOKEN:-}"
}

# ── Telegram ──────────────────────────────────────────────────────────────────
ask_telegram() {
  h1 "Telegram (optional)"
  info "Connect a Telegram bot to chat with Limbo from your phone."
  info "Create one at ${C_CYAN}https://t.me/BotFather${C_RESET}, then paste the token here."
  info "Press Enter to skip."
  echo
  read -rp "  Telegram bot token: " TELEGRAM_BOT_TOKEN
  export TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  clear 2>/dev/null || true

  echo "${C_BOLD}"
  cat <<'BANNER'
  ██╗     ██╗███╗   ███╗██████╗  ██████╗
  ██║     ██║████╗ ████║██╔══██╗██╔═══██╗
  ██║     ██║██╔████╔██║██████╔╝██║   ██║
  ██║     ██║██║╚██╔╝██║██╔══██╗██║   ██║
  ███████╗██║██║ ╚═╝ ██║██████╔╝╚██████╔╝
  ╚══════╝╚═╝╚═╝     ╚═╝╚═════╝  ╚═════╝
BANNER
  echo "${C_RESET}"
  echo "${C_BOLD}Personal memory agent — auth setup${C_RESET}"
  echo

  check_prereqs

  if [ -f "$ENV_FILE" ]; then
    warn ".env already exists at $ENV_FILE — this will overwrite it."
    read -rp "  Continue? [y/N] " ans
    [[ "$ans" =~ ^[Yy] ]] || { echo "Aborted."; exit 0; }
    echo
  fi

  h1 "Choose your AI provider"
  echo "  1) ${C_BOLD}Claude Code subscription${C_RESET}  — use your existing Claude Pro/Max sub"
  echo "  2) ${C_BOLD}Codex subscription${C_RESET}         — use your existing OpenAI sub"
  echo "  3) ${C_BOLD}OpenRouter${C_RESET}                 — 100+ models, one key"
  echo "  4) ${C_BOLD}Anthropic API key${C_RESET}          — pay-per-use, direct"
  echo
  local choice
  read -rp "  Choice [1-4]: " choice

  ask_telegram

  case "$choice" in
    1) auth_claude_code   ;;
    2) auth_codex         ;;
    3) auth_openrouter    ;;
    4) auth_anthropic_key ;;
    *) die "Invalid choice: $choice" ;;
  esac

  echo
  h1 "Ready"
  ok "Auth configured"
  ok ".env written"
  echo
  echo "Start Limbo:"
  echo "  ${C_BOLD}docker compose up -d${C_RESET}"
  echo
  if [ -n "${TELEGRAM_BOT_TOKEN:-}" ]; then
    info "Telegram: send your bot a message to complete pairing."
    echo
  fi
}

main "$@"
